% packagingPipeline

%% Standalone application
codeRepo = 'D:\code_repositories\minis';
appFile = [codeRepo filesep 'minis.m'];
contents = dir;
additionalFiles = [];
for iFile = 1:numel(contents)
  if ~strcmpi(contents(iFile).name(1), '.')
    additionalFiles{numel(additionalFiles)+1,1} = contents(iFile).name; %#ok<*SAGROW>
  end
end
compiler.build.standaloneApplication(appFile,...
  'ExecutableName','minis',...
  'AdditionalFiles',additionalFiles,...
  'OutputDir','D:\code_repositories\minisStandalone',...
  'TreatInputsAsNumeric','On',...
  'CustomHelpTextFile','',...
  'EmbedArchive','on',...
  'ExecutableIcon',[codeRepo filesep 'splashScreen.jpg'],...
  'ExecutableSplashScreen',[codeRepo filesep 'splashScreen.jpg'],...
  'ExecutableVersion','1.0',...
  'Verbose','On');